name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - uses: iterative/setup-cml@v2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # â­ Create Streamlit secrets from GitHub Secrets
    - name: Create Streamlit secrets
      run: |
        mkdir -p ~/.streamlit
        echo "\
GOOGLE_API_KEY = \"${{ secrets.GOOGLE_API_KEY }}\"
GROQ_API_KEY = \"${{ secrets.GROQ_API_KEY }}\"" > ~/.streamlit/secrets.toml

    - name: Run main file
      run: |
        python main.py

    - name: Run Tests
      continue-on-error: true
      run: |
        python -m unittest discover
